import {lazy} from "react";
import {IAlgoData} from "../../../types/global";

// 알고리즘 메타데이터는 여기서만 관리한다. 콘텐츠 모듈은 lazy import로 분리해
// 홈/목록 화면에서는 불러오지 않는다 (초기 번들 축소).
// sections의 en/ko 문자열은 각 언어로 렌더된 본문 h2 헤딩과 정확히 일치해야
// 사이드바/TOC/검색 앵커(slug)가 맞는다.
// 배열 순서가 사이드바·pager의 진행 순서다 — 계보순. sampling 은 roadmap(PRM 계열) →
// 트리(RRT 계열) → 최적 트리(RRT* 계열) → batch(FMT*→BIT*→…→FCIT*) → kinodynamic
// (SST→Kinodynamic→LQR) 순 — LQR 이 SST 를 전제하므로 kinodynamic 그룹을 뒤에 묶는다.
// graph search 는 기반 탐색(BFS→Dijkstra→A*) →
// grid 가속(JPS) → any-angle(Theta* 계열) → incremental·anytime(D* Lite→ARA*→AD*) →
// 연속 상태(Hybrid A*).
const data: IAlgoData[] = [
    // ---- Graph search ----
    {
        slug: "bfs",
        title: {en: "BFS", ko: "BFS"},
        category: "search",
        supportedExample: {python: true, "c++": true},
        contents: lazy(() => import("./global/search/Bfs")),
        sections: [
            {en: "The Idea", ko: "아이디어"},
            {en: "Properties and Complexity", ko: "성질과 복잡도"},
            {en: "The Algorithm", ko: "알고리즘"},
            {en: "When Hops Lie", ko: "최소 hop이 최단이 아닐 때"},
            {en: "Demo", ko: "Demo"},
            {en: "Implementation", ko: "Implementation"},
            {en: "References", ko: "References"},
        ],
    },
    {
        slug: "dijkstra",
        title: {en: "Dijkstra", ko: "Dijkstra"},
        category: "search",
        supportedExample: {python: true, "c++": true},
        contents: lazy(() => import("./global/search/Dijkstra")),
        sections: [
            {en: "From BFS to Dijkstra", ko: "BFS에서 Dijkstra로"},
            {en: "Properties and Complexity", ko: "성질과 복잡도"},
            {en: "The Algorithm", ko: "알고리즘"},
            {en: "Why Greedy Works", ko: "Greedy가 왜 통하는가"},
            {en: "Demo", ko: "Demo"},
            {en: "Implementation", ko: "Implementation"},
            {en: "References", ko: "References"},
        ],
    },
    {
        slug: "astar",
        title: {en: "A*", ko: "A*"},
        category: "search",
        supportedExample: {python: true, "c++": true},
        contents: lazy(() => import("./global/search/Astar")),
        sections: [
            {en: "From Dijkstra to A*", ko: "Dijkstra에서 A*로"},
            {en: "Properties and Complexity", ko: "성질과 복잡도"},
            {en: "The Algorithm", ko: "알고리즘"},
            {en: "Heuristics", ko: "Heuristic"},
            {en: "Why A* Is Optimal", ko: "A*는 왜 최적인가"},
            {en: "Demo", ko: "Demo"},
            {en: "Implementation", ko: "Implementation"},
            {en: "References", ko: "References"},
        ],
    },
    {
        slug: "jps",
        title: {en: "Jump Point Search", ko: "Jump Point Search"},
        category: "search",
        supportedExample: {python: true, "c++": true},
        contents: lazy(() => import("./global/search/Jps")),
        sections: [
            {en: "Symmetry Is the Enemy", ko: "대칭이 적이다"},
            {en: "Properties and Complexity", ko: "성질과 복잡도"},
            {en: "The Algorithm", ko: "알고리즘"},
            {en: "Demo", ko: "Demo"},
            {en: "Implementation", ko: "Implementation"},
            {en: "References", ko: "References"},
        ],
    },
    {
        slug: "theta_star",
        title: {en: "Theta*", ko: "Theta*"},
        category: "search",
        supportedExample: {python: true, "c++": true},
        contents: lazy(() => import("./global/search/ThetaStar")),
        sections: [
            {en: "Grids Lie About Distance", ko: "격자는 거리를 왜곡한다"},
            {en: "Properties and Complexity", ko: "성질과 복잡도"},
            {en: "The Algorithm", ko: "알고리즘"},
            {en: "Demo", ko: "Demo"},
            {en: "Implementation", ko: "Implementation"},
            {en: "References", ko: "References"},
        ],
    },
    {
        slug: "lazy_theta_star",
        title: {en: "Lazy Theta*", ko: "Lazy Theta*"},
        category: "search",
        supportedExample: {python: true, "c++": true},
        contents: lazy(() => import("./global/search/LazyThetaStar")),
        sections: [
            {en: "Assume First, Verify at Expansion", ko: "일단 가정하고, 확장할 때 확인한다"},
            {en: "Properties and Complexity", ko: "성질과 복잡도"},
            {en: "The Algorithm", ko: "알고리즘"},
            {en: "Demo", ko: "Demo"},
            {en: "Implementation", ko: "Implementation"},
            {en: "References", ko: "References"},
        ],
    },
    {
        slug: "visibility_astar",
        title: {en: "Visibility A*", ko: "Visibility A*"},
        category: "search",
        supportedExample: {python: true, "c++": true},
        contents: lazy(() => import("./global/search/VisibilityAstar")),
        sections: [
            {en: "From Shortcut to Successor", ko: "지름길에서 successor로"},
            {en: "Properties and Complexity", ko: "성질과 복잡도"},
            {en: "The Algorithm", ko: "알고리즘"},
            {en: "Not the True Optimum", ko: "참 최적은 아니다"},
            {en: "Demo", ko: "Demo"},
            {en: "Implementation", ko: "Implementation"},
            {en: "References", ko: "References"},
        ],
    },
    {
        slug: "anya",
        title: {en: "Anya", ko: "Anya"},
        category: "search",
        supportedExample: {python: true, "c++": true},
        contents: lazy(() => import("./global/search/Anya")),
        sections: [
            {en: "Turning at Corners", ko: "모서리에서 꺾는다"},
            {en: "Properties and Complexity", ko: "성질과 복잡도"},
            {en: "The Algorithm", ko: "알고리즘"},
            {en: "Demo", ko: "Demo"},
            {en: "Implementation", ko: "Implementation"},
            {en: "References", ko: "References"},
        ],
    },
    {
        slug: "dstar_lite",
        title: {en: "D* Lite", ko: "D* Lite"},
        category: "search",
        supportedExample: {python: true, "c++": true},
        contents: lazy(() => import("./global/search/DstarLite")),
        sections: [
            {en: "Planning Without a Map", ko: "지도 없이 계획하기"},
            {en: "Backward Search and the g/rhs Pair", ko: "Backward 탐색과 g/rhs"},
            {en: "Properties and Complexity", ko: "성질과 복잡도"},
            {en: "The Algorithm", ko: "알고리즘"},
            {en: "Why Repair Is Cheap", ko: "수리가 싼 이유"},
            {en: "Demo", ko: "Demo"},
            {en: "Implementation", ko: "Implementation"},
            {en: "References", ko: "References"},
        ],
    },
    {
        slug: "ara_star",
        title: {en: "ARA*", ko: "ARA*"},
        category: "search",
        supportedExample: {python: true, "c++": true},
        contents: lazy(() => import("./global/search/AraStar")),
        sections: [
            {en: "From Weighted A* to Anytime", ko: "Weighted A*에서 Anytime으로"},
            {en: "Properties and Complexity", ko: "성질과 복잡도"},
            {en: "The Algorithm", ko: "알고리즘"},
            {en: "Why the Bound Holds", ko: "한계가 성립하는 이유"},
            {en: "Demo", ko: "Demo"},
            {en: "Implementation", ko: "Implementation"},
            {en: "References", ko: "References"},
        ],
    },
    {
        slug: "ad_star",
        title: {en: "AD*", ko: "AD*"},
        category: "search",
        supportedExample: {python: true, "c++": true},
        contents: lazy(() => import("./global/search/AdStar")),
        sections: [
            {en: "Two Axes, One Planner", ko: "두 축, 하나의 planner"},
            {en: "Properties and Complexity", ko: "성질과 복잡도"},
            {en: "The Algorithm", ko: "알고리즘"},
            {en: "Demo", ko: "Demo"},
            {en: "Implementation", ko: "Implementation"},
            {en: "References", ko: "References"},
        ],
    },
    {
        slug: "hybrid_astar",
        title: {en: "Hybrid A*", ko: "Hybrid A*"},
        category: "search",
        supportedExample: {python: true, "c++": true},
        contents: lazy(() => import("./global/search/HybridAstar")),
        sections: [
            {en: "Leaving the Grid", ko: "격자를 떠나며"},
            {en: "Properties and Complexity", ko: "성질과 복잡도"},
            {en: "The Algorithm", ko: "알고리즘"},
            {en: "Demo", ko: "Demo"},
            {en: "Implementation", ko: "Implementation"},
            {en: "References", ko: "References"},
        ],
    },
    // ---- Sampling-based ----
    {
        slug: "prm",
        title: {en: "PRM", ko: "PRM"},
        category: "sampling",
        supportedExample: {python: true, "c++": true},
        contents: lazy(() => import("./global/sampling/Prm")),
        sections: [
            {en: "Sample, Connect, Query", ko: "뿌리고, 잇고, 묻는다"},
            {en: "Properties and Complexity", ko: "성질과 복잡도"},
            {en: "The Algorithm", ko: "알고리즘"},
            {en: "Demo", ko: "Demo"},
            {en: "Implementation", ko: "Implementation"},
            {en: "References", ko: "References"},
        ],
    },
    {
        slug: "prm_star",
        title: {en: "PRM*", ko: "PRM*"},
        category: "sampling",
        supportedExample: {python: true, "c++": true},
        contents: lazy(() => import("./global/sampling/PrmStar")),
        sections: [
            {en: "The Radius That Knows n", ko: "n을 아는 반경"},
            {en: "Properties and Complexity", ko: "성질과 복잡도"},
            {en: "The Algorithm", ko: "알고리즘"},
            {en: "Demo", ko: "Demo"},
            {en: "Implementation", ko: "Implementation"},
            {en: "References", ko: "References"},
        ],
    },
    {
        slug: "rrt",
        title: {en: "RRT", ko: "RRT"},
        category: "sampling",
        supportedExample: {python: true, "c++": true},
        contents: lazy(() => import("./global/sampling/Rrt")),
        sections: [
            {en: "Pulled by the Void", ko: "빈 공간이 끌어당긴다"},
            {en: "Properties and Complexity", ko: "성질과 복잡도"},
            {en: "The Algorithm", ko: "알고리즘"},
            {en: "Demo", ko: "Demo"},
            {en: "Implementation", ko: "Implementation"},
            {en: "References", ko: "References"},
        ],
    },
    {
        slug: "rrt_connect",
        title: {en: "RRT-Connect", ko: "RRT-Connect"},
        category: "sampling",
        supportedExample: {python: true, "c++": true},
        contents: lazy(() => import("./global/sampling/RrtConnect")),
        sections: [
            {en: "Extend Meets Connect", ko: "EXTEND와 CONNECT가 만난다"},
            {en: "Properties and Complexity", ko: "성질과 복잡도"},
            {en: "The Algorithm", ko: "알고리즘"},
            {en: "Demo", ko: "Demo"},
            {en: "Implementation", ko: "Implementation"},
            {en: "References", ko: "References"},
        ],
    },
    {
        slug: "rrt_star",
        title: {en: "RRT*", ko: "RRT*"},
        category: "sampling",
        supportedExample: {python: true, "c++": true},
        contents: lazy(() => import("./global/sampling/RrtStar")),
        sections: [
            {en: "Choose Parent, Then Rewire", ko: "부모를 고르고, 다시 배선한다"},
            {en: "Properties and Complexity", ko: "성질과 복잡도"},
            {en: "The Algorithm", ko: "알고리즘"},
            {en: "Demo", ko: "Demo"},
            {en: "Implementation", ko: "Implementation"},
            {en: "References", ko: "References"},
        ],
    },
    {
        slug: "informed_rrt_star",
        title: {en: "Informed RRT*", ko: "Informed RRT*"},
        category: "sampling",
        supportedExample: {python: true, "c++": true},
        contents: lazy(() => import("./global/sampling/InformedRrtStar")),
        sections: [
            {en: "From Everywhere to the Ellipse", ko: "전 공간에서 타원으로"},
            {en: "Properties and Complexity", ko: "성질과 복잡도"},
            {en: "The Algorithm", ko: "알고리즘"},
            {en: "Demo", ko: "Demo"},
            {en: "Implementation", ko: "Implementation"},
            {en: "References", ko: "References"},
        ],
    },
    {
        slug: "fast_rrt",
        title: {en: "Fast-RRT", ko: "Fast-RRT"},
        category: "sampling",
        supportedExample: {python: true, "c++": true},
        contents: lazy(() => import("./global/sampling/FastRrt")),
        sections: [
            {en: "Three Accelerations on the RRT* Tree", ko: "RRT* 트리에 얹는 가속 셋"},
            {en: "Properties and Complexity", ko: "성질과 복잡도"},
            {en: "The Algorithm", ko: "알고리즘"},
            {en: "Demo", ko: "Demo"},
            {en: "Implementation", ko: "Implementation"},
            {en: "References", ko: "References"},
        ],
    },
    {
        slug: "fmt_star",
        title: {en: "FMT*", ko: "FMT*"},
        category: "sampling",
        supportedExample: {python: true, "c++": true},
        contents: lazy(() => import("./global/sampling/FmtStar")),
        sections: [
            {en: "From Rewiring to Marching Order", ko: "rewire에서 행진 순서로"},
            {en: "Properties and Complexity", ko: "성질과 복잡도"},
            {en: "The Algorithm", ko: "알고리즘"},
            {en: "Demo", ko: "Demo"},
            {en: "Implementation", ko: "Implementation"},
            {en: "References", ko: "References"},
        ],
    },
    {
        slug: "bit_star",
        title: {en: "BIT*", ko: "BIT*"},
        category: "sampling",
        supportedExample: {python: true, "c++": true},
        contents: lazy(() => import("./global/sampling/BitStar")),
        sections: [
            {en: "From Informed Samples to an Edge Queue", ko: "informed 표본에서 간선 큐로"},
            {en: "Properties and Complexity", ko: "성질과 복잡도"},
            {en: "The Algorithm", ko: "알고리즘"},
            {en: "Demo", ko: "Demo"},
            {en: "Implementation", ko: "Implementation"},
            {en: "References", ko: "References"},
        ],
    },
    {
        slug: "abit_star",
        title: {en: "ABIT*", ko: "ABIT*"},
        category: "sampling",
        supportedExample: {python: true, "c++": true},
        contents: lazy(() => import("./global/sampling/AbitStar")),
        sections: [
            {en: "Rushing the Batch, Then Tightening", ko: "배치를 서둘러 훑고, 조인다"},
            {en: "Properties and Complexity", ko: "성질과 복잡도"},
            {en: "The Algorithm", ko: "알고리즘"},
            {en: "Demo", ko: "Demo"},
            {en: "Implementation", ko: "Implementation"},
            {en: "References", ko: "References"},
        ],
    },
    {
        slug: "ait_star",
        title: {en: "AIT*", ko: "AIT*"},
        category: "sampling",
        supportedExample: {python: true, "c++": true},
        contents: lazy(() => import("./global/sampling/AitStar")),
        sections: [
            {en: "From a Straight Line to a Reverse Search", ko: "직선에서 역방향 탐색으로"},
            {en: "Properties and Complexity", ko: "성질과 복잡도"},
            {en: "The Algorithm", ko: "알고리즘"},
            {en: "Demo", ko: "Demo"},
            {en: "Implementation", ko: "Implementation"},
            {en: "References", ko: "References"},
        ],
    },
    {
        slug: "eit_star",
        title: {en: "EIT*", ko: "EIT*"},
        category: "sampling",
        supportedExample: {python: true, "c++": true},
        contents: lazy(() => import("./global/sampling/EitStar")),
        sections: [
            {en: "From Cost to Cost and Effort", ko: "비용에서 비용과 노력으로"},
            {en: "Properties and Complexity", ko: "성질과 복잡도"},
            {en: "The Algorithm", ko: "알고리즘"},
            {en: "Demo", ko: "Demo"},
            {en: "Implementation", ko: "Implementation"},
            {en: "References", ko: "References"},
        ],
    },
    {
        slug: "fcit_star",
        title: {en: "FCIT*", ko: "FCIT*"},
        category: "sampling",
        supportedExample: {python: true, "c++": true},
        contents: lazy(() => import("./global/sampling/FcitStar")),
        sections: [
            {en: "From a Radius Graph to a Complete Graph", ko: "반경 그래프에서 완전 그래프로"},
            {en: "Properties and Complexity", ko: "성질과 복잡도"},
            {en: "The Algorithm", ko: "알고리즘"},
            {en: "Demo", ko: "Demo"},
            {en: "Implementation", ko: "Implementation"},
            {en: "References", ko: "References"},
        ],
    },
    {
        slug: "sst",
        title: {en: "SST", ko: "SST"},
        category: "sampling",
        supportedExample: {python: true, "c++": true},
        contents: lazy(() => import("./global/sampling/Sst")),
        sections: [
            {en: "Growing Without a Steering Function", ko: "steer 없이 트리를 키운다"},
            {en: "Properties and Complexity", ko: "성질과 복잡도"},
            {en: "The Algorithm", ko: "알고리즘"},
            {en: "Demo", ko: "Demo"},
            {en: "Implementation", ko: "Implementation"},
            {en: "References", ko: "References"},
        ],
    },
    {
        slug: "kinodynamic_rrt_star",
        title: {en: "Kinodynamic RRT*", ko: "Kinodynamic RRT*"},
        category: "sampling",
        supportedExample: {python: true, "c++": true},
        contents: lazy(() => import("./global/sampling/KinodynamicRrtStar")),
        sections: [
            {en: "From Straight Edges to Optimal Trajectories", ko: "직선 간선에서 최적 궤적으로"},
            {en: "Properties and Complexity", ko: "성질과 복잡도"},
            {en: "The Algorithm", ko: "알고리즘"},
            {en: "Demo", ko: "Demo"},
            {en: "Implementation", ko: "Implementation"},
            {en: "References", ko: "References"},
        ],
    },
    {
        slug: "lqr_rrt_star",
        title: {en: "LQR-RRT*", ko: "LQR-RRT*"},
        category: "sampling",
        supportedExample: {python: true, "c++": true},
        contents: lazy(() => import("./global/sampling/LqrRrtStar")),
        sections: [
            {en: "Steering Derived from a Regulator", ko: "조절기가 steering을 만든다"},
            {en: "Properties and Complexity", ko: "성질과 복잡도"},
            {en: "The Algorithm", ko: "알고리즘"},
            {en: "Demo", ko: "Demo"},
            {en: "Implementation", ko: "Implementation"},
            {en: "References", ko: "References"},
        ],
    },
    // ---- Local planning (구현 예정) ----
    {slug: "dwa", title: {en: "DWA", ko: "DWA"}, category: "local"},
    {slug: "pure_pursuit", title: {en: "Pure Pursuit", ko: "Pure Pursuit"}, category: "local"},
    {slug: "vfh", title: {en: "VFH", ko: "VFH"}, category: "local"},
    {slug: "mpc", title: {en: "MPC", ko: "MPC"}, category: "local"},
    // ---- Multi-agent (구현 예정) ----
    {slug: "prioritized_astar", title: {en: "Prioritized A*", ko: "Prioritized A*"}, category: "multi"},
    {slug: "joint_astar", title: {en: "Joint-space A*", ko: "Joint-space A*"}, category: "multi"},
    {slug: "cbs", title: {en: "CBS", ko: "CBS"}, category: "multi"},
]

export default data
