import {lazy} from "react";
import {IAlgoData} from "../../../types/global";

// 알고리즘 메타데이터는 여기서만 관리한다. 콘텐츠 모듈은 lazy import로 분리해
// 홈/목록 화면에서는 불러오지 않는다 (초기 번들 축소).
// sections의 en/ko 문자열은 각 언어로 렌더된 본문 h2 헤딩과 정확히 일치해야
// 사이드바/TOC/검색 앵커(slug)가 맞는다.
// 배열 순서가 사이드바·pager의 진행 순서다 — 계보순: 기반 탐색(BFS→Dijkstra→A*) →
// grid 가속(JPS) → any-angle(Theta* 계열) → incremental·anytime(D* Lite→ARA*→AD*) →
// 연속 상태(Hybrid A*).
const data: IAlgoData[] = [
    // ---- Graph search ----
    {
        slug: "bfs",
        title: {en: "BFS", ko: "BFS"},
        category: "search",
        supportedExample: {python: true, "c++": true},
        contents: lazy(() => import("./global/search/Bfs")),
        sections: [
            {en: "The Idea", ko: "아이디어"},
            {en: "Properties and Complexity", ko: "성질과 복잡도"},
            {en: "The Algorithm", ko: "알고리즘"},
            {en: "When Hops Lie", ko: "최소 hop이 최단이 아닐 때"},
            {en: "Demo", ko: "Demo"},
            {en: "Implementation", ko: "Implementation"},
            {en: "References", ko: "References"},
        ],
    },
    {
        slug: "dijkstra",
        title: {en: "Dijkstra", ko: "Dijkstra"},
        category: "search",
        supportedExample: {python: true, "c++": true},
        contents: lazy(() => import("./global/search/Dijkstra")),
        sections: [
            {en: "From BFS to Dijkstra", ko: "BFS에서 Dijkstra로"},
            {en: "Properties and Complexity", ko: "성질과 복잡도"},
            {en: "The Algorithm", ko: "알고리즘"},
            {en: "Why Greedy Works", ko: "Greedy가 왜 통하는가"},
            {en: "Demo", ko: "Demo"},
            {en: "Implementation", ko: "Implementation"},
            {en: "References", ko: "References"},
        ],
    },
    {
        slug: "astar",
        title: {en: "A*", ko: "A*"},
        category: "search",
        supportedExample: {python: true, "c++": true},
        contents: lazy(() => import("./global/search/Astar")),
        sections: [
            {en: "From Dijkstra to A*", ko: "Dijkstra에서 A*로"},
            {en: "Properties and Complexity", ko: "성질과 복잡도"},
            {en: "The Algorithm", ko: "알고리즘"},
            {en: "Heuristics", ko: "Heuristic"},
            {en: "Why A* Is Optimal", ko: "A*는 왜 최적인가"},
            {en: "Demo", ko: "Demo"},
            {en: "Implementation", ko: "Implementation"},
            {en: "References", ko: "References"},
        ],
    },
    {
        slug: "jps",
        title: {en: "Jump Point Search", ko: "Jump Point Search"},
        category: "search",
        supportedExample: {python: true, "c++": true},
        contents: lazy(() => import("./global/search/Jps")),
        sections: [
            {en: "Symmetry Is the Enemy", ko: "대칭이 적이다"},
            {en: "Properties and Complexity", ko: "성질과 복잡도"},
            {en: "The Algorithm", ko: "알고리즘"},
            {en: "Demo", ko: "Demo"},
            {en: "Implementation", ko: "Implementation"},
            {en: "References", ko: "References"},
        ],
    },
    {
        slug: "theta_star",
        title: {en: "Theta*", ko: "Theta*"},
        category: "search",
        supportedExample: {python: true, "c++": true},
        contents: lazy(() => import("./global/search/ThetaStar")),
        sections: [
            {en: "Grids Lie About Distance", ko: "격자는 거리를 왜곡한다"},
            {en: "Properties and Complexity", ko: "성질과 복잡도"},
            {en: "The Algorithm", ko: "알고리즘"},
            {en: "Demo", ko: "Demo"},
            {en: "Implementation", ko: "Implementation"},
            {en: "References", ko: "References"},
        ],
    },
    {
        slug: "lazy_theta_star",
        title: {en: "Lazy Theta*", ko: "Lazy Theta*"},
        category: "search",
        supportedExample: {python: true, "c++": true},
        contents: lazy(() => import("./global/search/LazyThetaStar")),
        sections: [
            {en: "Assume First, Verify at Expansion", ko: "일단 가정하고, 확장할 때 확인한다"},
            {en: "Properties and Complexity", ko: "성질과 복잡도"},
            {en: "The Algorithm", ko: "알고리즘"},
            {en: "Demo", ko: "Demo"},
            {en: "Implementation", ko: "Implementation"},
            {en: "References", ko: "References"},
        ],
    },
    {
        slug: "visibility_astar",
        title: {en: "Visibility A*", ko: "Visibility A*"},
        category: "search",
        supportedExample: {python: true, "c++": true},
        contents: lazy(() => import("./global/search/VisibilityAstar")),
        sections: [
            {en: "From Shortcut to Successor", ko: "지름길에서 successor로"},
            {en: "Properties and Complexity", ko: "성질과 복잡도"},
            {en: "The Algorithm", ko: "알고리즘"},
            {en: "Not the True Optimum", ko: "참 최적은 아니다"},
            {en: "Demo", ko: "Demo"},
            {en: "Implementation", ko: "Implementation"},
            {en: "References", ko: "References"},
        ],
    },
    {
        slug: "anya",
        title: {en: "Anya", ko: "Anya"},
        category: "search",
        supportedExample: {python: true, "c++": true},
        contents: lazy(() => import("./global/search/Anya")),
        sections: [
            {en: "Turning at Corners", ko: "모서리에서 꺾는다"},
            {en: "Properties and Complexity", ko: "성질과 복잡도"},
            {en: "The Algorithm", ko: "알고리즘"},
            {en: "Demo", ko: "Demo"},
            {en: "Implementation", ko: "Implementation"},
            {en: "References", ko: "References"},
        ],
    },
    {
        slug: "dstar_lite",
        title: {en: "D* Lite", ko: "D* Lite"},
        category: "search",
        supportedExample: {python: true, "c++": true},
        contents: lazy(() => import("./global/search/DstarLite")),
        sections: [
            {en: "Planning Without a Map", ko: "지도 없이 계획하기"},
            {en: "Backward Search and the g/rhs Pair", ko: "Backward 탐색과 g/rhs"},
            {en: "Properties and Complexity", ko: "성질과 복잡도"},
            {en: "The Algorithm", ko: "알고리즘"},
            {en: "Why Repair Is Cheap", ko: "수리가 싼 이유"},
            {en: "Demo", ko: "Demo"},
            {en: "Implementation", ko: "Implementation"},
            {en: "References", ko: "References"},
        ],
    },
    {
        slug: "ara_star",
        title: {en: "ARA*", ko: "ARA*"},
        category: "search",
        supportedExample: {python: true, "c++": true},
        contents: lazy(() => import("./global/search/AraStar")),
        sections: [
            {en: "From Weighted A* to Anytime", ko: "Weighted A*에서 Anytime으로"},
            {en: "Properties and Complexity", ko: "성질과 복잡도"},
            {en: "The Algorithm", ko: "알고리즘"},
            {en: "Why the Bound Holds", ko: "한계가 성립하는 이유"},
            {en: "Demo", ko: "Demo"},
            {en: "Implementation", ko: "Implementation"},
            {en: "References", ko: "References"},
        ],
    },
    {
        slug: "ad_star",
        title: {en: "AD*", ko: "AD*"},
        category: "search",
        supportedExample: {python: true, "c++": true},
        contents: lazy(() => import("./global/search/AdStar")),
        sections: [
            {en: "Two Axes, One Planner", ko: "두 축, 하나의 planner"},
            {en: "Properties and Complexity", ko: "성질과 복잡도"},
            {en: "The Algorithm", ko: "알고리즘"},
            {en: "Demo", ko: "Demo"},
            {en: "Implementation", ko: "Implementation"},
            {en: "References", ko: "References"},
        ],
    },
    {
        slug: "hybrid_astar",
        title: {en: "Hybrid A*", ko: "Hybrid A*"},
        category: "search",
        supportedExample: {python: true, "c++": true},
        contents: lazy(() => import("./global/search/HybridAstar")),
        sections: [
            {en: "Leaving the Grid", ko: "격자를 떠나며"},
            {en: "Properties and Complexity", ko: "성질과 복잡도"},
            {en: "The Algorithm", ko: "알고리즘"},
            {en: "Demo", ko: "Demo"},
            {en: "Implementation", ko: "Implementation"},
            {en: "References", ko: "References"},
        ],
    },
    // ---- Sampling-based ----
    {slug: "prm", title: {en: "PRM", ko: "PRM"}, category: "sampling"},
    {slug: "prm_star", title: {en: "PRM*", ko: "PRM*"}, category: "sampling"},
    {slug: "rrt", title: {en: "RRT", ko: "RRT"}, category: "sampling"},
    {slug: "rrt_connect", title: {en: "RRT-Connect", ko: "RRT-Connect"}, category: "sampling"},
    {slug: "rrt_star", title: {en: "RRT*", ko: "RRT*"}, category: "sampling"},
    {slug: "informed_rrt_star", title: {en: "Informed RRT*", ko: "Informed RRT*"}, category: "sampling"},
    {slug: "fast_rrt", title: {en: "Fast-RRT", ko: "Fast-RRT"}, category: "sampling"},
    {slug: "kinodynamic_rrt_star", title: {en: "Kinodynamic RRT*", ko: "Kinodynamic RRT*"}, category: "sampling"},
    {slug: "lqr_rrt_star", title: {en: "LQR-RRT*", ko: "LQR-RRT*"}, category: "sampling"},
    {slug: "fmt_star", title: {en: "FMT*", ko: "FMT*"}, category: "sampling"},
    {slug: "bit_star", title: {en: "BIT*", ko: "BIT*"}, category: "sampling"},
    {slug: "abit_star", title: {en: "ABIT*", ko: "ABIT*"}, category: "sampling"},
    {slug: "ait_star", title: {en: "AIT*", ko: "AIT*"}, category: "sampling"},
    {slug: "eit_star", title: {en: "EIT*", ko: "EIT*"}, category: "sampling"},
    {slug: "fcit_star", title: {en: "FCIT*", ko: "FCIT*"}, category: "sampling"},
    {slug: "sst", title: {en: "SST", ko: "SST"}, category: "sampling"},
    // ---- Local planning (구현 예정) ----
    {slug: "dwa", title: {en: "DWA", ko: "DWA"}, category: "local"},
    {slug: "pure_pursuit", title: {en: "Pure Pursuit", ko: "Pure Pursuit"}, category: "local"},
    {slug: "vfh", title: {en: "VFH", ko: "VFH"}, category: "local"},
    {slug: "mpc", title: {en: "MPC", ko: "MPC"}, category: "local"},
    // ---- Multi-agent (구현 예정) ----
    {slug: "prioritized_astar", title: {en: "Prioritized A*", ko: "Prioritized A*"}, category: "multi"},
    {slug: "joint_astar", title: {en: "Joint-space A*", ko: "Joint-space A*"}, category: "multi"},
    {slug: "cbs", title: {en: "CBS", ko: "CBS"}, category: "multi"},
]

export default data
