"""Hybrid A* — kinodynamic search over the continuous SE(2) pose space.

Dolgov, Thrun, Montemerlo & Diebel (2008). Unlike the grid searches, the state is a
continuous ``Pose`` (x, y, theta). Successors are constant-curvature motion primitives
(arcs) generated by the planner's own vehicle model (min turn radius, arc length,
#steering angles, optional reverse); the map only answers footprint collision at a pose
(``SE2CollisionSpace``). The closed set keys on a discretized (x, y, theta) bin, so the
continuous search stays finite. The heuristic is the straight-line Euclidean distance to
goal (admissible, w = 1); there is no Reeds-Shepp/Dubins heuristic and no analytic
expansion (resolution-complete / resolution-suboptimal — the goal is reached within a
position + heading tolerance, Dolgov et al. 2008).

Determinism note: x, y come from sin/cos (arc integration), which IEEE-754 does NOT
require to be correctly-rounded. CPython's ``math`` and C++ ``std`` wrap the SAME libm,
so on one machine the search runs identically: path_cost / expanded_nodes match and the
trace event stream agrees in order/count and to serialization precision (the two writers
format floats differently). This is a same-libm property, not an IEEE cross-platform
guarantee. ``math`` scalars (never ``numpy``, whose vectorized sin/cos may differ) and
``sqrt`` (correctly-rounded) not ``hypot`` (relaxed-accuracy) keep it so.

Does NOT reuse ``_discrete`` (its reconstruct/emit are Cell-typed); Hybrid A* keys on a
Pose bin and reconstructs a dense sub-pose polyline.
"""

from __future__ import annotations

import heapq
import itertools
import math
import time

from navigation.core.capabilities import Capability, SE2CollisionSpace
from navigation.core.params import ParamSet
from navigation.core.planner import GlobalPlanner
from navigation.core.trace import TraceRecorder
from navigation.core.types import Footprint, PlanResult, PlanStats, Pose

_TWO_PI = 2.0 * math.pi
# Below this |curvature| an arc is integrated as a straight segment (odd num_steering
# gives an exact kappa = 0; the guard also covers near-zero even-split endpoints).
_STRAIGHT_EPS = 1e-9

_Bin = tuple[int, int, int]


def _wrap_angle(theta: float) -> float:
    # [0, 2*pi). floor delegates to libm; identical to the C++ mirror on one machine.
    return theta - _TWO_PI * math.floor(theta / _TWO_PI)


def _ang_diff(a: float, b: float) -> float:
    # Shortest angular difference magnitude, in [0, pi]. No trig.
    d = _wrap_angle(a - b)
    if d > math.pi:
        d -= _TWO_PI
    return abs(d)


def _integrate(p: Pose, kappa: float, length: float) -> Pose:
    # Advance a pose by a constant-curvature arc of signed length. theta is additive
    # (no trig for heading); x, y integrate the arc exactly (Dolgov et al. 2008).
    x, y, theta = p
    theta2 = theta + kappa * length
    if abs(kappa) < _STRAIGHT_EPS:
        return (x + length * math.cos(theta), y + length * math.sin(theta), theta2)
    return (
        x + (math.sin(theta2) - math.sin(theta)) / kappa,
        y - (math.cos(theta2) - math.cos(theta)) / kappa,
        theta2,
    )


class HybridAStar(GlobalPlanner[Pose, "SE2CollisionSpace[Pose]"]):
    def __init__(self, params: ParamSet) -> None:
        super().__init__(params)
        self._min_turn_radius = params.get_float("min_turn_radius")
        self._arc_step = params.get_float("arc_step")
        self._num_steering = params.get_int("num_steering")
        self._theta_bins = params.get_int("theta_bins")
        self._xy_resolution = params.get_float("xy_resolution")
        self._footprint = Footprint(params.get_float("footprint_radius"))
        self._allow_reverse = params.get_bool("allow_reverse")
        self._reverse_penalty = params.get_float("reverse_penalty")
        self._steer_penalty = params.get_float("steer_penalty")
        self._goal_pos_tol = params.get_float("goal_pos_tolerance")
        self._goal_heading_tol = params.get_float("goal_heading_tolerance")

    @property
    def name(self) -> str:
        return "hybrid_astar"

    def required_capabilities(self) -> set[Capability]:
        return {Capability.SE2_COLLISION_SPACE}

    def plan(
        self,
        space: SE2CollisionSpace[Pose],
        start: Pose,
        goal: Pose,
        recorder: TraceRecorder | None = None,
    ) -> PlanResult[Pose]:
        t0 = time.monotonic()
        kappa_max = 1.0 / self._min_turn_radius
        bin_theta = _TWO_PI / self._theta_bins
        arc_step = self._arc_step
        # Sub-sampling spacing tied to CLEARANCE (footprint radius), floored at 2 so
        # consecutive footprint discs overlap (no tunnelling) and every arc emits >=2
        # chords (renders curved). Independent of the closed-set bin resolution.
        n_sub = max(2, math.ceil(arc_step / self._footprint.inscribed_radius))

        # Fixed order: forward fan by ascending kappa index, then reverse fan.
        # num_steering >= 2 guards the (num_steering - 1) denominator (config min 2).
        kappa_span = 2.0 * kappa_max / (self._num_steering - 1)
        curvatures = [-kappa_max + i * kappa_span for i in range(self._num_steering)]
        primitives: list[tuple[float, float, bool]] = [(k, arc_step, False) for k in curvatures]
        if self._allow_reverse:
            primitives += [(k, -arc_step, True) for k in curvatures]

        gx0 = self._xy_resolution
        theta_bins = self._theta_bins

        def bin_of(p: Pose) -> _Bin:
            # Planner-internal pure arithmetic on world coords — never map.world_to_cell.
            return (
                math.floor(p[0] / gx0),
                math.floor(p[1] / gx0),
                math.floor(_wrap_angle(p[2]) / bin_theta) % theta_bins,
            )

        def h(p: Pose) -> float:
            dx, dy = p[0] - goal[0], p[1] - goal[1]
            return math.sqrt(dx * dx + dy * dy)  # sqrt, NOT hypot (relaxed-accuracy)

        def is_goal(p: Pose) -> bool:
            dx, dy = p[0] - goal[0], p[1] - goal[1]
            return dx * dx + dy * dy <= self._goal_pos_tol**2 and (
                _ang_diff(p[2], goal[2]) <= self._goal_heading_tol
            )

        footprint = self._footprint
        reverse_penalty = self._reverse_penalty
        steer_penalty = self._steer_penalty

        counter = itertools.count()  # stable (f, seq) tie-break, keeps heap comparable
        start_bin = bin_of(start)
        g: dict[_Bin, float] = {start_bin: 0.0}
        pose_of: dict[_Bin, Pose] = {start_bin: start}  # best continuous pose per bin
        # Incoming dense arc per bin: (parent bin, sub-poses parent-exclusive..this bin).
        came_from: dict[_Bin, tuple[_Bin, list[Pose]]] = {}
        closed: set[_Bin] = set()
        frontier: list[tuple[float, int, _Bin]] = [(h(start), next(counter), start_bin)]
        expanded = 0
        found = False
        goal_bin: _Bin = start_bin

        while frontier:
            _, _, b = heapq.heappop(frontier)
            if b in closed:  # stale duplicate: bin already settled
                continue
            closed.add(b)
            p = pose_of[b]  # expand the bin's best pose -> came_from stays continuous
            expanded += 1
            if recorder is not None:
                recorder.node_expanded(p, g[b])
            if is_goal(p):
                found = True
                goal_bin = b
                break
            for kappa, length, reverse in primitives:
                # Sub-sample the arc: reuse the sub-poses for BOTH collision and viz.
                subs: list[Pose] = []
                blocked = False
                for j in range(1, n_sub + 1):
                    s = _integrate(p, kappa, length * (j / n_sub))
                    if space.is_collision(footprint, s):
                        blocked = True
                        break
                    subs.append(s)
                if blocked:
                    continue
                child = subs[-1]
                b2 = bin_of(child)
                if b2 in closed:
                    continue
                abs_l = abs(length)
                cost = abs_l * (reverse_penalty if reverse else 1.0) + steer_penalty * abs(
                    kappa
                ) * abs_l
                cand = g[b] + cost
                if b2 not in g or cand < g[b2]:
                    g[b2] = cand
                    pose_of[b2] = child
                    came_from[b2] = (b, subs)
                    if recorder is not None:
                        recorder.candidate_evaluated(child, cand)
                        # Arc renders as a chain of straight edge_added chords (dense ->
                        # smooth curve). Parent of the first sub-pose is the expanded pose.
                        chord = abs_l / n_sub
                        parent = p
                        for s in subs:
                            recorder.edge_added(s, parent, chord)
                            parent = s
                    heapq.heappush(frontier, (cand + h(child), next(counter), b2))

        runtime = time.monotonic() - t0
        if not found:
            if recorder is not None:
                recorder.planning_finished(
                    False,
                    {"runtime_sec": runtime, "path_cost": 0.0, "expanded_nodes": float(expanded)},
                )
            return PlanResult(success=False, stats=PlanStats(expanded_nodes=expanded))

        # Walk came_from goal->start, collecting dense arcs, then emit start + arcs forward.
        arcs: list[list[Pose]] = []
        b = goal_bin
        while b != start_bin:
            parent_bin, subs = came_from[b]
            arcs.append(subs)
            b = parent_bin
        path: list[Pose] = [start]
        for subs in reversed(arcs):
            path.extend(subs)
        cost = g[goal_bin]
        if recorder is not None:
            recorder.path_found(path)
            recorder.planning_finished(
                True,
                {"runtime_sec": runtime, "path_cost": cost, "expanded_nodes": float(expanded)},
            )
        return PlanResult(True, path, cost, PlanStats(expanded_nodes=expanded))
