#pragma once

#include <set>
#include <string>

#include "navigation/core/planner.hpp"

namespace navigation::global_planning {

// Hybrid A* (Dolgov, Thrun, Montemerlo & Diebel 2008): kinodynamic search over the
// continuous SE(2) pose space. Unlike the grid searches, the state is a continuous
// Pose (x, y, theta). Successors are constant-curvature motion primitives (arcs)
// generated by the planner's own vehicle model (min turn radius, arc length, #steering
// angles, optional reverse); the map only answers footprint collision at a pose
// (SE2CollisionSpace). The closed set keys on a discretized (x, y, theta) bin, so the
// continuous search stays finite. Heuristic is the straight-line Euclidean distance to
// goal (admissible, w = 1); no Reeds-Shepp/Dubins heuristic and no analytic expansion
// (resolution-complete / resolution-suboptimal — goal is reached within a position +
// heading tolerance).
//
// Determinism note: x, y come from sin/cos (arc integration), which IEEE-754 does NOT
// require to be correctly-rounded. CPython's math and C++ std wrap the SAME libm, so on
// one machine the search runs identically — path_cost / expanded_nodes match and the
// trace event stream agrees in order/count and to serialization precision (the two
// writers format floats differently). This is a same-libm property, not an IEEE
// cross-platform guarantee.
class HybridAStarPlanner final : public core::SE2CollisionPlanner {
 public:
  explicit HybridAStarPlanner(core::ParamSet params)
      : core::SE2CollisionPlanner(std::move(params)) {}
  std::string name() const override { return "hybrid_astar"; }
  std::set<core::Capability> required_capabilities() const override {
    return {core::Capability::SE2_COLLISION_SPACE};
  }
  core::PlanResult<core::Pose> plan(core::SE2CollisionSpace<core::Pose>& space,
                                    const core::Pose& start, const core::Pose& goal,
                                    core::TraceRecorder* recorder) override;
};

}  // namespace navigation::global_planning
